### ISSUE TITLE
DatepickerProps shortcuts Type error

### ISSUE THREAD

**Issue by Huugiii** [elreco/vue-tailwind-datepicker#100]
**Describe the bug**
shortcuts props type invalid when boolean is given.

**To Reproduce**
1. Create Vue 3 Composition (script setup lang="ts")
2. Add VueTailwindDatepicker component
3. Add props ```:shortcuts="false"``` => ```Error : Type 'boolean' is not assignable to type '() => { label: string; atClick: () => Date[]; }[]'.ts(2322)```

**To Fix**
In type.d.ts : 
```js
shortcuts?: () => { label: string; atClick: () => Date[] }[]
become
shortcuts?: boolean | (() => { label: string; atClick: () => Date[] }[])
```

**Comment by elreco** [comment]
Fixed in the 1.4.6 👍🏼
