### ISSUE TITLE
How can I load only one language pack individually? 

### ISSUE THREAD

**Issue by goophps** [elreco/vue-tailwind-datepicker#103]
hi, After the code is running, many JS language packs can be seen in the resources of the browser. What can I do to load only one language pack file?

**Comment by xibman** [comment]
@goophps It will be available in the next release

**Comment by elreco** [comment]
Fixed in the 1.5.0

**Comment by goophps** [comment]
thank you

**Comment by goophps** [comment]
How should I use it?

**Comment by goophps** [comment]
I upgraded to the new version 1.5.0, and many language pack files were still loaded after packaging and building.
