### ISSUE TITLE
Date manually entered with keyboard in the input field isn't reflected on the calendar

### ISSUE THREAD

**Issue by rwinsinger** [elreco/vue-tailwind-datepicker#110]
**Describe the bug**
When you type in a date or range of dates in the input field, those dates aren't reflected in the calendar display.  You can't type spaces in the input field, so it isn't possible to format date/time or two dates as they show up when selecting dates via the calendar.

**To Reproduce**
This can be tested on the demo page https://vue-tailwind-datepicker/demo.html
1. Click into the input field
2. The placeholder shows the format it expects, but you can't type in the date/time format since spaces aren't allowed.
3. Type in just a date such as "2023-09-29" and hit enter.  Now click back on the input field to bring up the calendar and it doesn't show that date.  Same behavior if you attempt a range "2023-09-01~2023-09-29"

Note: If you select dates from the calendar, you are able to manually update the dates in the input field and those are reflected on the calendar.  You aren't able to just click anywhere, but can click at the end of the second date/time and use the arrow keys to move back through the input to change values.  Changes to the dates will be automatically updated on the calendar.

**Expected behavior**
The user should be able to manually enter a date or date range in the input field and that would be reflected on the calendar.  

**Screenshots**
![example-date-input](https://github.com/elreco/vue-tailwind-datepicker/assets/3832853/91dda595-e0d9-4499-9367-6c99c1a72a38)

**Desktop & mobile (please complete the following information):**
 - Browser: Chrome 117.0.5983.132
 - Library version: 1.4.6

**Comment by xibman** [comment]
@rwinsinger  on it ! 
Fix already in pipeline !
