### ISSUE TITLE
Is it possible to change the  appearance of the input?

### ISSUE THREAD

**Issue by tvianney** [elreco/vue-tailwind-datepicker#126]
I'm trying to change the size of the input as well as the bg color with tailwind css class but it's not working properly. What is the right way to do it if it's even possible?

**Comment by xibman** [comment]
@tvianney  yes check the doc : https://vue-tailwind-datepicker.com/props.html#input-classes

**Comment by tvianney** [comment]
Right!!! I must be blind :/ Thank you!
