### ISSUE TITLE
Inconsistent behavior when disabling future dates after selecting a date

### ISSUE THREAD

**Issue by ryuzaki369** [elreco/vue-tailwind-datepicker#129]
**Describe the bug**
When attempting to disable future dates, the functionality works properly until a date is selected. After selecting a date, the disabled dates are no longer functioning as expected.

**To Reproduce**
1. Navigate to the date picker functionality.
2. Disable all future dates.
3. Select a date from the date picker.
4. Attempt to select a future date

**Expected behavior**
The functionality should consistently disable all dates beyond the selected date, maintaining the initial restriction on future dates.

**Screenshots**
<img width="444" alt="image" src="https://github.com/elreco/vue-tailwind-datepicker/assets/29703113/6bf473f4-0109-4470-9dca-014b73347b06">

<img width="400" alt="image" src="https://github.com/elreco/vue-tailwind-datepicker/assets/29703113/20a0656c-8e5f-4499-953c-dd87f5622cdb">

**Desktop & mobile (please complete the following information):**
 - Browser: Chrome
 - Library version: 1.6.1

**Comment by seobrain** [comment]
Hey,
Kindly asking if there are any chances this can be fixed in the next releases?
Love the component, but this issue is a blocker for the production usage.
Many thanks in advance!

**Comment by Slubby** [comment]
Hey, I dug into the code and found something called disableInRange. It's not in the docs, but adding it to the component did the trick.

**Comment by smerchkz** [comment]
i describe this bug here https://github.com/elreco/vue-tailwind-datepicker/issues/114#issuecomment-1962407529

**Comment by ryuzaki369** [comment]
> Hey, I dug into the code and found something called `disableInRange`. It's not in the docs, but adding it to the component did the trick.

i confirm this is working
