### ISSUE TITLE
Start/End date string not assignable to modelValue type

### ISSUE THREAD

**Issue by gedeondoescode** [elreco/vue-tailwind-datepicker#15]
**Describe the bug**
`dataValue` returns a String TypeError when using it as an object

**To Reproduce**
1. Install latest package with npm
2. Create script tag with Typescript set as the language
3. Import `ref` from Vue and `VueTailwindDatepicker`
4. Create ` const dataValue` and add to v-model
5. See error

**Expected behavior**
No error indicating that `startDate` & `endDate` having strings is accepted.

**Screenshots**
![Screenshot_20221106_105312](https://user-images.githubusercontent.com/75461444/200181360-ee42b88c-c9b8-4c4e-aa14-3b37e9a7338e.png)

**Comment by elreco** [comment]
Thank you for your help @gedeondoescode 
It's fixed on the [v1.1.1](https://github.com/elreco/vue-tailwind-datepicker/releases/tag/1.1.1)
