### ISSUE TITLE
Disabled dates are accessible after selecting the date

### ISSUE THREAD

**Issue by ElizabethCF01** [elreco/vue-tailwind-datepicker#154]
**Describe the bug**
In a single date picker without input, if any date is disable, in the past or in the future and an available date is selected, then all the dates become accessible.

**To Reproduce**
1. Add a single date picker, disable any date.
2. Select a date from the date picker.
3. Attempt to select a date that must be disabled

**Expected behavior**
Keep dates disabled according to the function definition passed as 'disable-date' parameter in single date pickers after select a date

**Screenshots**
![image](https://github.com/user-attachments/assets/2ca5ee57-403f-4c90-a145-c450f928b290)

**Playground**
[https://stackblitz.com/edit/vue-tailwind-datepicker-onuvfj?file=src%2Fcomponents%2FPlayground.vue](url)

**Desktop & mobile **
 - Browser chrome
 - Library version 1.7.3

**Comment by fabokenneth** [comment]
i have the same issue

**Comment by cgtarmenta** [comment]
This can be worked around by passing ````disable-in-range```` prop
@ElizabethCF01 I've forked your stackblitz and updated it.
https://stackblitz.com/edit/vue-tailwind-datepicker-jusekn?file=src%2Fcomponents%2FPlayground.vue

```vue
<script setup>
import { ref } from 'vue';
const dateValue = ref('');
import 'dayjs/locale/fr';
import VueTailwindDatepicker from 'vue-tailwind-datepicker';

function dDate(date) {
  return date < new Date();
}
</script>

<template>
  <VueTailwindDatepicker
    i18n="fr"
    v-model="dateValue"
    as-single
    no-input
    :disable-date="dDate"
    disable-in-range  
  />
</template>
```

**Comment by ElizabethCF01** [comment]
> This can be worked around by passing `disable-in-range` prop @ElizabethCF01 I've forked your stackblitz and updated it. https://stackblitz.com/edit/vue-tailwind-datepicker-jusekn?file=src%2Fcomponents%2FPlayground.vue
> 
> ```
> <script setup>
> import { ref } from 'vue';
> const dateValue = ref('');
> import 'dayjs/locale/fr';
> import VueTailwindDatepicker from 'vue-tailwind-datepicker';
> 
> function dDate(date) {
>   return date < new Date();
> }
> </script>
> 
> <template>
>   <VueTailwindDatepicker
>     i18n="fr"
>     v-model="dateValue"
>     as-single
>     no-input
>     :disable-date="dDate"
>     disable-in-range  
>   />
> </template>
> ```

thank you so much @cgtarmenta

**Comment by ElizabethCF01** [comment]
Sorry i did't notice that the pr is still open, I just checked the forked playground and saw that it worked correctly with your changes

**Comment by cgtarmenta** [comment]
@ElizabethCF01 the fix was merged and released, this can be closed now

**Comment by sira87** [comment]
Is this issue still ongoing? I've updated to 1.7.3 and I can still select disabled dates after selecting a date.

Using `disable-in-range` as a fix seems to disable the wrong dates after selecting a date.

**Comment by cgtarmenta** [comment]
@sira87 can you provide an stackblitz or something to reproduce your exact error?

**Comment by sira87** [comment]
> can you provide an stackblitz or something to reproduce your exact error?

Hey, I've opened a new issue #159 about this with some code snippets and screenshots. Would you mind checking it? Thank you!
