### ISSUE TITLE
Input triggers 1Password Chrome extension

### ISSUE THREAD

**Issue by jbrooksuk** [elreco/vue-tailwind-datepicker#2]
![CleanShot 2022-09-14 at 10 33 33](https://user-images.githubusercontent.com/246103/190118322-b3c4a043-fa7e-45f6-8955-2935e3cec399.png)

I haven't identified exactly why it's doing this, but clicking into the input triggers the 1Password Chrome extension.

**Comment by elreco** [comment]
Oh, yet the input is a text type. Will check it and add a fix if I can find a solution. 
I don't know if it's possible to prevent any chrome extension from being "linked" to the input

**Comment by jbrooksuk** [comment]
Yeah, I'm not sure what more can be done here. It may be worth contacting 1Password though? It's very hard to search for a solution.

**Comment by elreco** [comment]
I think I can try to add a type date here:

https://github.com/elreco/vue-tailwind-datepicker/blob/main/src/VueTailwindDatePicker.vue#L1214

**Comment by jbrooksuk** [comment]
Thanks!

**Comment by jbrooksuk** [comment]
It may also be worth adding `autocomplete="do_not_complete"` or something... `autocomplete="off"` is not guaranteed to work in Chrome.

**Comment by elreco** [comment]
@jbrooksuk Hi :) Please go to your 1password extension settings and tell me if you selected All items here:

<img width="1188" alt="image" src="https://user-images.githubusercontent.com/42843594/196957320-77468ad8-3013-4ccb-848b-4a40b30ed6c8.png">
