### ISSUE TITLE
Tab into input causes error

### ISSUE THREAD

**Issue by smccoy78** [elreco/vue-tailwind-datepicker#28]
**Describe the bug**
Whenever you tab into the datepicker component that has a value, an error is thrown in the console. Occurs on demo site and playground.

**To Reproduce**
1. Set focus on input by tabbing in to it.

**Expected behavior**
No thrown error

**Version**
1.1.5
 
**Screenshot**
![Screenshot 2022-11-22 at 5 24 02 PM](https://user-images.githubusercontent.com/2486409/203438016-7063720e-86f5-4448-a4a9-e59effeca126.jpg)

**Comment by shengslogar** [comment]
This is still an issue in `1.1.7`, except it's now "w is not a function".

**Comment by elreco** [comment]
@shengslogar oh yes you are right, thank you for your help 🙏 you can open a PR
