### ISSUE TITLE
Display date picker inline

### ISSUE THREAD

**Issue by ghost** [elreco/vue-tailwind-datepicker#3]
Hello,

I need to display the date picker inline in a popup without input field. 

Is there anyway I can do that?

**Comment by alexsyvolap** [comment]
@elreco Hey! How long you'll implement this feature?

**Comment by alexsyvolap** [comment]
@elreco hey! Is there any news?

**Comment by elreco** [comment]
@alexsyvolap sorry it's still in progress :( I will keep working on it this week end

**Comment by elreco** [comment]
@alexsyvolap Hey 😄 Please tell me what do you think about it: 

https://vue-tailwind-datepicker-git-inline-datepicker-tomoe-gozen.vercel.app/props.html#without-input

#36 

(It can be displayed with a date range too btw)

**Comment by alexsyvolap** [comment]
@elreco wow, it's beautiful, but in mobile version you forgot hide "Cancel" button
<img width="307" alt="image" src="https://user-images.githubusercontent.com/80973788/206925286-8472fcf9-093c-401b-bee7-d7ae0d6ca7dc.png">

**Comment by elreco** [comment]
@alexsyvolap Oh yes! thank you! Fixed

**Comment by alexsyvolap** [comment]
@elreco perfect, thank you too for this feature! :)

**Comment by elreco** [comment]
@alexsyvolap https://github.com/elreco/vue-tailwind-datepicker/releases/tag/1.2.0
