### ISSUE TITLE
want to use shortcuts within asSingle mode

### ISSUE THREAD

**Issue by fexli** [elreco/vue-tailwind-datepicker#35]
Using the asSingle props will disable the shortcuts and the rightmost date column, even I use shortcuts="true". 
hope shortcuts will appear with asSingle or at least it can be controlled by shortcuts props alone

**Comment by elreco** [comment]
@fexli you can't use shortcuts with asSingle because shortcuts are built to select a range date.

**Comment by chipit24** [comment]
But you can have a range selection even with a single picker: https://vue-tailwind-datepicker.com/props.html#use-range. Would having the shortcuts in that case not be valid?

**Comment by elreco** [comment]
@chipit24 you are right! I enabled shortcuts when use-range & as-single are true.
You can test it with the 1.2.2 version. Thank you
