### ISSUE TITLE
Emit changes month/year/date

### ISSUE THREAD

**Issue by alexsyvolap** [elreco/vue-tailwind-datepicker#38]
Add emits for change month/year/date. When click on next button or select from opened months or years list, also when select date.

**Comment by alexsyvolap** [comment]
@elreco hey! Can you add this in one of the next patches, please? Me need know when user click to Datepicker buttons (changed month/year or select date).

Thank you

**Comment by elreco** [comment]
@alexsyvolap yes I will work on it next week 👍🏼

**Comment by duyn-stanford** [comment]
This pull request seems to have broken pre-populated date fields. In my edit form when I have an existing date, e.g., 2023-01-09, and try to populate the form with this field, the date shown is 2000-01-01 instead of 2023-01-09. Was working fine in version 1.2.6 but now broken in 1.2.10.
