### ISSUE TITLE
No focus style for as-single

### ISSUE THREAD

**Issue by elikeiz** [elreco/vue-tailwind-datepicker#40]
Hi,
In as-single mode, there is no highlight style for the day buttons when they have focus (making it hard to navigate with tabs).

As a work around, I've add these classes to the root for now:
`[&_.vtd-datepicker-date:focus]:border [&_.vtd-datepicker-date:focus]:ring [&_.vtd-datepicker-date:focus]:border-vtd-primary-500 [&_.vtd-datepicker-date:focus]:ring-vtd-primary-100 [&_.vtd-datepicker-date:focus]:bg-vtd-primary-100 [&_.vtd-datepicker-date:focus]:text-black`

Thanks

**Comment by elreco** [comment]
Hello @elikeiz 

thank you for your work around, you make a PR of this if you want 😄

**Comment by elreco** [comment]
Fixed in the 1.2.4
