### ISSUE TITLE
Is the v-model really reactive?

### ISSUE THREAD

**Issue by ilzrv** [elreco/vue-tailwind-datepicker#44]
I want to reset the dates to the default value.

I do this in my code, but the old date remains in the interface, while the new value is in the model itself. I reproduced it [here](https://stackblitz.com/edit/vue-tailwind-datepicker-1cnjsm?file=src%2Fcomponents%2FPlayground.vue).

<img width="414" alt="image" src="https://user-images.githubusercontent.com/28765966/210068610-ec40a655-3041-4a7b-8958-ab3584932dc6.png">

**Comment by ilzrv** [comment]
We can use manual re-rendering (via v-if disable and enable) and everything works, but it doesn't look like the right way.

**Comment by elreco** [comment]
Thank you for your help. I am working on it

**Comment by tpoxa** [comment]
@input event seems to be not triggering, I think it should right?

**Comment by Atantares** [comment]
Hi @elreco 
how's everything going? Looks like I have the same bug

**Comment by rizahoemae** [comment]
it might be better if the datepicker had a clear or reset button under the "today, yesterday, etc" range to reset it to the default values we already defined in the v-model, probably(?)

**Comment by Fuitad** [comment]
Heya,

has there been any progress on this?

**Comment by xibman** [comment]
version 1.5.1 solve model reactivity
