### ISSUE TITLE
Component doesnt set initial value

### ISSUE THREAD

**Issue by zoomyboy** [elreco/vue-tailwind-datepicker#49]
**Describe the bug**
If I set the modelValue before mounting the component, events for updating the input value in the field (pickerValue) are not triggered.
This is happening if the component is updated "silently", e.g. when using vue-router with nuxt. PickerValue is still "".

As soon as I open the calendar (clicking on the field), the correct value appears in the input.

**Expected behavior**
The input field of the picker should update with the initial modelValue.

**Comment by elreco** [comment]
Can we close this issue @zoomyboy ?

**Comment by zoomyboy** [comment]
As I said in the PR: This might not address all the possible configurations and formats but fixes the bug at least.
So yes, close it ;) Thanks
