### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by khprzybyl** [elreco/vue-tailwind-datepicker#5]
**Is your feature request related to a problem? Please describe.**
Hey 👋 
I love your date-picker, and I appreciate your work. 
I have Vue3 app with typescript and I've noticed that your date-picker doesn't provide typescript support. 
Do you consider adding it in the future? 

**Describe the solution you'd like**
to have this error gone
<img width="999" alt="image" src="https://user-images.githubusercontent.com/101949054/195160398-54c76ce4-4e17-4b2f-bdff-944bb66616fb.png">

**Additional context**
I am not an experienced developer yet, but if you consider working with a junior I can try to help

**Comment by elreco** [comment]
Thank you for you support 😄 
You are right, Typescript is not supported yet but it's planed!

Feel free to start a new PR if you want to add some typescript. That would be awesome if you want to be a part of this work ❤️
