### ISSUE TITLE
"h is not a function" when `noInput` prop is set

### ISSUE THREAD

**Issue by shengslogar** [elreco/vue-tailwind-datepicker#52]
**Describe the bug**

Using shortcuts throws an error when `no-input` prop is set. Error seems to be thrown from `close()` here.

https://github.com/elreco/vue-tailwind-datepicker/blob/5ee24f0b618000eda07a04221aba79f611deca7d/src/VueTailwindDatePicker.vue#L1066-L1074

**To Reproduce**
```
<vue-tailwind-datepicker no-input />
```

Clicking on any shortcut throws an error.

**Expected behavior**
N/A

**Screenshots**
![Screenshot 2023-01-23 at 02 58 30@2x](https://user-images.githubusercontent.com/4350009/213958792-534b5e78-2779-4b2c-83c6-2e1051b9f2d8.jpg)
![Screenshot 2023-01-23 at 03 02 02@2x](https://user-images.githubusercontent.com/4350009/213959056-581bff18-61db-490a-9d91-b5bfd4be03ff.jpg)

**Desktop & mobile (please complete the following information):**
 - N/A
 - v1.1.8

**Comment by elreco** [comment]
Fixed in the 1.2.8, thank you
