### ISSUE TITLE
New Vue project and Playground version not working "onBeforeMount is not defined"

### ISSUE THREAD

**Issue by Falibur** [elreco/vue-tailwind-datepicker#54]
When setting up a new Vue project and install 'vue-tailwind-datepicker' like mentioned in the tutorial https://dev.to/elreco/add-a-tailwind-datepicker-to-your-vue-3-application-57j2 the datepicker won't work. It produces "onBeforeMount is not defined" in the console.

**To Reproduce**
1. Set up a new Vue project (latest versioin)
2. Follow the steps of https://dev.to/elreco/add-a-tailwind-datepicker-to-your-vue-3-application-57j2
3. Run the project
4. Open the console to see the error

Also to be seen in the playground: https://stackblitz.com/edit/vue-tailwind-datepicker?file=src%2Fcomponents%2FPlayground.vue

**Comment by elreco** [comment]
Hello 👋 you can add the 1.2.9 version. It's fixed. Thank you 🙏

**Comment by Falibur** [comment]
Nice! :1st_place_medal: quickly solved! Thank you
