### ISSUE TITLE
Using custom prefixed tailwind css classes

### ISSUE THREAD

**Issue by Falibur** [elreco/vue-tailwind-datepicker#55]
When using this component inside an existing website or application it is sometimes useful to add a css prefix for every tailwind class.
Tailwind itself also provides this feature, so would be nice to have it included in this component as well.

To use the component like the following:
`<VueTailwindDatePicker as-single :use-range="false" i18n="en" :formatter="formatter tailwind-prefix="tw-" />"`

Link to the Tailwind prefix configuration option:
https://tailwindcss.com/docs/configuration#prefix

**Comment by Falibur** [comment]
Nice work @elreco and @Previesam!!
I can just use this in my new project where we have existing css classes and are forced to prefix the tailwind ones.
Btw, in my proposal I was thinking of a configurable tailwind prefix. That could be handy, when having multiple tailwind configurations, but that situation will be more uncommon so guess that this change is already much helpful for most!

**Comment by jjjrmy** [comment]
we are using a different prefix in our project, is there any way to use that?

**Comment by kokoforbes** [comment]
@elreco Please add configuration to add tailwind prefix like "tw-"
