### ISSUE TITLE
Monday as first day of the week

### ISSUE THREAD

**Issue by JapSeyz** [elreco/vue-tailwind-datepicker#6]
In Denmark, Monday is shown as the first day of the week.

I cannot find an option for setting whether it should be sunday or monday in the package at this time.

**Comment by elreco** [comment]
I don't think there is a work around. I will work on this feature soon, it will be available in the next version. I keep you update

**Comment by elreco** [comment]
@LeftCoder this idea is very good! We can add a props called `weekStart`?

**Comment by elreco** [comment]
@LeftCoder bro it works perfectly, so nice! 

https://github.com/elreco/vue-tailwind-datepicker/pull/31

**Comment by LeftCoder** [comment]
Since there already is a pull request for that let's move the conversation to #31
