### ISSUE TITLE
Setting default date for single datepicker does not display correct date in input field.

### ISSUE THREAD

**Issue by duyn-stanford** [elreco/vue-tailwind-datepicker#63]
**Describe the bug**
When setting a default date for a single datepicker, the wrong date is displayed in the input field. This was working in version 1.2.6 but no longer works in version 1.2.11.

**To Reproduce**
```
<script setup>
import { ref } from 'vue';
import VueTailwindDatepicker from 'vue-tailwind-datepicker';

const dateValue = ref('2023-02-28');
</script>

<template>
    <vue-tailwind-datepicker
        v-model="dateValue"
        as-single
        :formatter="{
            date: 'YYYY-MM-DD',
            month: 'MMMM',
        }"
        :shortcuts="false"
    />
</template>
```
**Expected behavior**
Expect input field to have default date of 2023-02-28. Instead input field shows 2000-01-01.

**Screenshots**
![Screenshot 2023-02-03 at 4 10 27 PM](https://user-images.githubusercontent.com/89502875/216733508-f587ec3b-c606-41c1-ab21-e746824c9c1c.png)

**Desktop & mobile (please complete the following information):**
 - Library version [e.g. 3.0.0]

**Comment by fabiobulgarella** [comment]
I Confirm. Have the same problem, cannot set a default date.
