### ISSUE TITLE
Disabled dates are still selectable

### ISSUE THREAD

**Issue by mikelerch** [elreco/vue-tailwind-datepicker#7]
**Describe the bug**
Disabling dates doesn't seem to work.

**To Reproduce**
You can reproduce it using the example in the docs as well https://vue-tailwind-datepicker.com/props.html#disable-date

**Expected behavior**
The dates before today (and after 2022) should not be selectable.

**Comment by elreco** [comment]
@mikelerch fixed in the [1.0.10 release](https://github.com/elreco/vue-tailwind-datepicker/releases/tag/1.0.10)
