### ISSUE TITLE
Component in nuxt 3 does not work properly

### ISSUE THREAD

**Issue by alexisdechiara** [elreco/vue-tailwind-datepicker#76]
**Describe the bug**
The component does not appear as it should, there is no style and when you click on it the modal is bugged

**To Reproduce**
1. Install vue tailwind datepicker, dayjs, tailwindcss and forms plugin for tailwind
2. Add forms plugin in tailwind.config.js : 
```
...
plugins: [require('@tailwindcss/forms')],
```
4. Add vue tailwind datepicker as plugin in the /public directory :
```
import VueTailwindDatepicker from 'vue-tailwind-datepicker';

export default defineNuxtPlugin((nuxtApp) => {
    nuxtApp.vueApp.use(VueTailwindDatepicker)
})
```
5. create a page with a demo code inside :
```
<script setup>
import { ref } from 'vue'
const dateValue = ref([])
</script>

<template>
  <vue-tailwind-datepicker input-classes="block mb-2 text-sm font-medium text-green-700 dark:text-green-500" v-model="dateValue" />
</template>
```
6. See error : go to screenshot

**Expected behavior**
Should work like [here](https://vue-tailwind-datepicker.com/props.html#input-classes)

**Screenshots**
input :
![image](https://user-images.githubusercontent.com/48689074/229121739-4f26fbd3-a7c6-4581-b0cf-e13e6dc43935.png)

When click :
![image](https://user-images.githubusercontent.com/48689074/229121869-b699169a-3e94-473a-b821-a3dd52f36afe.png)

**Desktop & mobile (please complete the following information):**
 - Browser : Chrome
 - Browser version 112.0.5615.49

**Comment by mikeashi** [comment]
you have to configure tailwind correctly:

in your tailwind.config.js add:

```
...
content: [
    `@/components/**/*.{vue,js,ts}`,
    `@/layouts/**/*.vue`,
    `@/pages/**/*.vue`,
    `@/composables/**/*.{js,ts}`,
    `@/plugins/**/*.{js,ts}`,
    `@/utils/**/*.{js,ts}`,
    `@/App.{js,ts,vue}`,
    `@/app.{js,ts,vue}`,
    `@/Error.{js,ts,vue}`,
    `@/error.{js,ts,vue}`,
    "./node_modules/vue-tailwind-datepicker/**/*.js",
  ],
  ....
```

**Comment by janpmz** [comment]
Doesn't work in nuxt3 for me.
