### ISSUE TITLE
Calendar icon customization

### ISSUE THREAD

**Issue by jongirard** [elreco/vue-tailwind-datepicker#77]
It appears that currently there is no way to customize/change the "calendar" icon that is used on the component. 

**Describe the solution you'd like**
It would be great if there was a way to customize/change the "calendar" icon or otherwise somehow extend the theme to allow for this icon to be changed to a custom component or SVG/asset.

**Describe alternatives you've considered**
N/A

**Additional context**
<img width="252" alt="Screen Shot 2023-03-31 at 11 46 14 AM" src="https://user-images.githubusercontent.com/579976/229204403-c59de48c-8a80-42c2-9186-7adee7674d12.png">

**Comment by xibman** [comment]
@jongirard version 1.5.1 add a slot for icon customisation 

https://vue-tailwind-datepicker.com/props.html#inputicon-slot
