### ISSUE TITLE
Width of the calendar is not responsive

### ISSUE THREAD

**Issue by Pajicc** [elreco/vue-tailwind-datepicker#84]
Calendar content takes half of the calendar wrapper on MD screens.

Steps to reproduce:
1. Open vue-tailwind-datepicker demo
2. Scroll to single date example
3. Open up the calendar and reduce the screen size a bit

<img width="745" alt="image" src="https://user-images.githubusercontent.com/18647471/236178418-3b0af162-2fa1-4598-b4a2-427e7d2d58c1.png">

**Comment by fabiobulgarella** [comment]
Confirm. It happens between >=768px and  <1024px, so in the "md:" tailwind breakpoint.
I think the problem is in the element .vtd-datepicker > div > div > div:
- it has the class "md:w-1/2" while should be something like "md:w-60".

**Comment by elreco** [comment]
I fixed this in the 1.4.5
