### ISSUE TITLE
Lazy load locale files

### ISSUE THREAD

**Issue by KevinXL** [elreco/vue-tailwind-datepicker#93]
First of all thanks for the lovely datepicker. I see that all the locale files are downloaded when the datepicker is loaded.

Is it possible to lazy load the files so only the locale that is needed is downloaded?
Or is it possible to group the locales in one file?

<img width="1008" alt="image" src="https://github.com/elreco/vue-tailwind-datepicker/assets/5447200/0ee2a52d-4f4d-457f-9f16-05f065b1a608">

**Comment by xibman** [comment]
@KevinXL  done with next release

**Comment by elreco** [comment]
Fixed in the 1.5.0
