### ISSUE TITLE
Update value outside component not updating UI

### ISSUE THREAD

**Issue by CoverID** [elreco/vue-tailwind-datepicker#94]
**Describe the bug**
```
<script setup>
import { ref } from 'vue'
const dateValue = ref([])

// UI not updating when change dateValue outside component
setTimeout(() => {
  dateValue.value = ...newValue;
}, 1000);
</script>

<template>
    <vue-tailwind-datepicker v-model="dateValue" />
</template>
```

**Expected behavior**
pickerValue has to be reactive/listen to any changes from modelValue, so if we change the v-model value outside the component then the ui will also be updated

**Comment by daedeloth** [comment]
Seconded.

**Comment by xibman** [comment]
@CoverID  @daedeloth  last version 1.5.1 solve the model reactivity problem
