### ISSUE TITLE
Slow loading in multiple languages

### ISSUE THREAD

**Issue by lushangkan** [elreco/vue-tailwind-datepicker#98]
**Describe the bug**
When using v-if to hide the datepicker, when opening it for the first time, the custom language will not be loaded immediately, and you need to close it and open it again several times before it is loaded.

**To Reproduce**
1. Set the datepicker language to Chinese
2. Use v-if to hide the datepicker
3. Open the datepicker

**Expected behavior**
Open the datepicker to load the language immediately

**Screenshots**
![screenshot](https://github.com/elreco/vue-tailwind-datepicker/assets/41252325/64b8ec3a-2c0d-4ee1-b866-6ac5e36aed13)

**Desktop & mobile (please complete the following information):**
 - Browser Edge
 - Library version 1.4.5

**Comment by elreco** [comment]
@lushangkan did you try using v-show?

**Comment by xibman** [comment]
@lushangkan solved in the next release with dynamic language loading

**Comment by elreco** [comment]
Fixed in the 1.5.0
